Repository skycoin/hardware-wallet, pull requests merged in 2019-04, with the labels that each got.

#154 fixes #142 - Refactor fsm.c for unit testing
  .travis.yml
  CONTRIBUTING.md
  tiny-firmware/firmware/error.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm.h
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, stdev, wip

#167 fixes #151 - Test cases for input validation
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  tiny-firmware/firmware/error.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/fsm_impl_REMOTE_10097.c
  tiny-firmware/firmware/protect.c
  tiny-firmware/firmware/protect.h
  tiny-firmware/firmware/test_fsm.c
Labels: stdev, wip

#175 refs #151 Test cases for SkyconAddress firmware message handler
  tiny-firmware/Makefile
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm.h
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/firmware/test_many_address_golden.c
  tiny-firmware/firmware/test_many_address_golden.h
Labels: Milestone v.1.0.0, stdev, wip

#181 Fixes #176 Update firmware message
  tiny-firmware/bootloader/bootloader.c
  tiny-firmware/bootloader/usb.c
  tiny-firmware/firmware/skywallet.c
Labels: Milestone v.1.0.0, bootloader, stdev, wip

#179 Fixes #125 new graphics assets device with Cloud
  tiny-firmware/gen/bitmaps.c
  tiny-firmware/gen/bitmaps/digit0.png
  tiny-firmware/gen/bitmaps/digit1.png
  tiny-firmware/gen/bitmaps/digit2.png
  tiny-firmware/gen/bitmaps/digit3.png
  tiny-firmware/gen/bitmaps/digit4.png
  tiny-firmware/gen/bitmaps/digit5.png
  tiny-firmware/gen/bitmaps/digit6.png
  tiny-firmware/gen/bitmaps/digit7.png
  tiny-firmware/gen/bitmaps/digit8.png
  tiny-firmware/gen/bitmaps/digit9.png
  tiny-firmware/gen/bitmaps/gears0.png
  tiny-firmware/gen/bitmaps/gears1.png
  tiny-firmware/gen/bitmaps/gears2.png
  tiny-firmware/gen/bitmaps/gears3.png
  tiny-firmware/gen/bitmaps/logo48.png
  tiny-firmware/gen/bitmaps/logo48_empty.png
  tiny-firmware/gen/bitmaps/skycoin_logo64.png
Labels: Milestone v.1.0.0, stdev, wip

#196 refs #171 Boundary checks for address test cases
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, stdev, wip

#195 product string from SKYCOIN to Skywallet
  tiny-firmware/bootloader/usb.c
  tiny-firmware/firmware/usb.c
Labels: Milestone v.1.0.0, bootloader, bug, firmware, stdev, wip

#190 fixes #188 - Fix pin codes with bad chars and equal length pass the pin check
  tiny-firmware/Makefile
  tiny-firmware/firmware/pinmatrix.c
  tiny-firmware/firmware/pinmatrix.h
  tiny-firmware/firmware/protect.c
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/firmware/test_main.c
  tiny-firmware/firmware/test_protect.c
  tiny-firmware/firmware/test_protect.h
Labels: Milestone v.1.0.0, stdev, wip

#203 Read device UUID ref #202
  CHANGELOG.md
  tiny-firmware/firmware/main.c
  tiny-firmware/firmware/storage.c
  tiny-firmware/memory.h
  tiny-firmware/serialno.c
Labels: Milestone v.1.0.0, bug, enhancement, firmware, security, stdev, wip
