Repository skycoin/hardware-wallet, pull requests merged in 2019-05, with the labels that each got.

#205 Device UUID fixes ref #202
  tiny-firmware/firmware/main.c
  tiny-firmware/firmware/storage.c
  tiny-firmware/firmware/storage.h
Labels: Milestone v.1.0.0, enhancement, firmware, security, stdev, wip

#185 Improve validations of input data for transaction signing
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/test_fsm.c
Labels: stdev, wip

#200 Get memprotect level ref #45
  FAQ.md
  images/skycoin_logo_inverted_bootloader.jpg
  tiny-firmware/bootloader/bootloader.c
  tiny-firmware/bootloader/usb.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/main.c
  tiny-firmware/memory.c
  tiny-firmware/memory.h
Labels: Milestone v.1.0.0, bootloader, enhancement, security, stdev, wip

#183 Create a firmware version deployment usable from makefile fixes #50
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  ci-scripts/version.sh
  releases/.gitkeep
  releases/README.md
  releases/bootloader/skycoin-bl.bin
  releases/firmware/skycoin-firmware-passphrase-experiment.bin
  releases/firmware/skycoin-firmware.bin
  releases/full-firmware/skycoin.bin
  releases/full-firmware/skywallet.bin
  tiny-firmware/Makefile
  tiny-firmware/Makefile.include
  tiny-firmware/VERSION
  tiny-firmware/bootloader/Makefile
  tiny-firmware/bootloader/VERSION
  tiny-firmware/bootloader/bootloader.c
  tiny-firmware/bootloader/bootloader.h
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/main.c
  tiny-firmware/firmware/recovery.c
  tiny-firmware/firmware/skywallet.h
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, enhancement, stdev, wip

#216 Gen address bug ref #215
  appveyor.yml
  tiny-firmware/firmware/fsm.c
Labels: Milestone v.1.0.0, bug, firmware, stdev, wip

#221 Fix an extra message send in fsm_msgSkycoinSignMessage ref #220
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
Labels: Milestone v.1.0.0, bug, firmware, security, stdev, wip

#214 AWS deploy ref #210
  .travis.yml
  CHANGELOG.md
Labels: Milestone v.1.0.0, enhancement, help wanted, stdev, wip

#222 Fix bug in skycoin sign message ref #219
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
Labels: Milestone v.1.0.0, bug, critical-security, firmware, stdev, wip

#218 Bug in sign message ref #217
  .travis.yml
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
Labels: Milestone v.1.0.0, bug, critical-security, stdev, wip

#223 fixes #217 Fix bug determining firmware and bootloader version number
  Makefile
  ci-scripts/version.sh
Labels: Milestone v.1.0.0, ci, stdev, wip

#226 fixes #224 S3 deploy folder
  .travis.yml
  COPYING
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, ci, stdev, wip

#237 fixes #235 - Improve getting started Instructions
  FAQ.md
  README.md
Labels: doc, stdev, wip
