Repository skycoin/hardware-wallet, pull requests merged in 2019-03, with the labels that each got.

#109 fixes #107 - Fix include paths
  .travis.yml
  CHANGELOG.md
  README.md
  tiny-firmware/Makefile
  tiny-firmware/Makefile.include
  tiny-firmware/emulator/Makefile
Labels: stdev, wip

#114 fixes #102 - Correct anchor links in README ToC
  .github/pull_request_template.md
  README.md
Labels: stdev, wip

#118 fixes #115 Restore bip39 library implementation
  Makefile
  skycoin-api/tools/bip39.c
  skycoin-api/tools/bip39.h
  skycoin-api/tools/bip39_english.h
  skycoin-api/tools/pbkdf2.c
  skycoin-api/tools/pbkdf2.h
  tiny-firmware/Makefile
Labels: stdev, wip

#106 External entropy generation and merge - fixes #88
  CHANGELOG.md
  FAQ.md
  README.md
  ci-scripts/install-osx.sh
  tiny-firmware/Makefile
  tiny-firmware/firmware/droplet.c
  tiny-firmware/firmware/entropy.c
  tiny-firmware/firmware/entropy.h
  tiny-firmware/firmware/error.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/reset.c
  tiny-firmware/firmware/reset.h
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, bug, critical-security, doc, firmware, help wanted, question, stdev, wip

#128 [firmware] fixes #124 - Verify language and set to English if empty
  CHANGELOG.md
  tiny-firmware/firmware/fsm.c
Labels: firmware, stdev, wip

#129 refs #64 - Project versionning scheme
  README.md
Labels: doc, stdev, wip

#137 fixes #17 - Skycoin branding graphics for SkyWallet devices
  CHANGELOG.md
  Makefile
  tiny-firmware/gen/bitmaps.c
  tiny-firmware/gen/bitmaps.h
  tiny-firmware/gen/bitmaps/generate.py
  tiny-firmware/gen/bitmaps/logo48.png
  tiny-firmware/gen/bitmaps/logo48_empty.png
  tiny-firmware/gen/bitmaps/logo64.png
  tiny-firmware/gen/bitmaps/logo64_empty.png
Labels: bootloader, stdev, wip

#149 Fixes #147 Change name windows to Skywallet
  .gitignore
  tiny-firmware/emulator/oled.c
  tiny-firmware/emulator/udp.c
Labels: Milestone v.1.0.0, emulator, stdev, wip

#150 fixes #111 Print 1.5 coins correctly
  tiny-firmware/firmware/droplet.c
  tiny-firmware/firmware/droplet.h
  tiny-firmware/firmware/test_droplet.c
Labels: stdev, wip

#152 Delete label by accident ref #146
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/test_fsm.c
Labels: Milestone v.1.0.0, bug, firmware, stdev, wip

#145 fixes #143 - Protobuff changes related to PR (if any)
  .github/pull_request_template.md
Labels: stdev, wip

#144 fixes #143 - Blank issue template
  .github/ISSUE_TEMPLATE/blank.md
Labels: stdev, wip

#94 Travis notifications for Telegram bot
  .gitignore
  .travis.yml
Labels: stdev, wip
