Repository skycoin/hardware-wallet, pull requests merged in 2019-02, with the labels that each got.

#43 License
  .gitignore
  COPYING
  skycoin-api/check_digest.h
  skycoin-api/skycoin_check_signature.c
  skycoin-api/skycoin_check_signature.h
  skycoin-api/skycoin_check_signature_tools.c
  skycoin-api/skycoin_check_signature_tools.h
  skycoin-api/skycoin_crypto.c
  skycoin-api/skycoin_crypto.h
  skycoin-api/test_skycoin_crypto.c
  skycoin-api/tools/memzero.c
  skycoin-api/tools/memzero.h
  skycoin-api/tools/ripemd160.h
  tiny-firmware/README.md
  tiny-firmware/bootloader/bootloader.c
  tiny-firmware/bootloader/signatures.c
  tiny-firmware/bootloader/usb.c
  tiny-firmware/emulator/oled.c
  tiny-firmware/firmware/factory_test.c
  tiny-firmware/firmware/factory_test.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm.h
  tiny-firmware/firmware/layout2.c
  tiny-firmware/firmware/layout2.h
  tiny-firmware/firmware/reset.c
  tiny-firmware/firmware/storage.c
  tiny-firmware/firmware/storage.h
  tiny-firmware/firmware/trezor.c
  tiny-firmware/firmware/usb.c
  tiny-firmware/memory.c
  tiny-firmware/memory.h
Labels: stdev, wip

#74 fixes #73 - Licensing revised
  tiny-firmware/emulator/oled.c
Labels: stdev, wip

#75 fixes #50 fixes #64 - Release process and Makefile targets
  Makefile
  README.md
  tiny-firmware/Makefile.include
  tiny-firmware/VERSION
  tiny-firmware/bootloader/VERSION
  tiny-firmware/bootloader/bootloader.h
  tiny-firmware/firmware/trezor.h
Labels: stdev, wip

#66 signed messages in hexdump format, not base 58 - fixes #65
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  skycoin-api/Makefile
  skycoin-api/check_digest.c
  skycoin-api/check_digest.h
  skycoin-api/test_skycoin_crypto.c
  tiny-firmware/Makefile
  tiny-firmware/Makefile.include
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/main.c
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/firmware/trezor.c
  tiny-firmware/firmware/trezor.h
  tiny-firmware/protob/messages.options
Labels: stdev, wip

#70 Reshape recovery seed for skycoin needs. ref #33
  CHANGELOG.md
  skycoin-api/trezor-tools/bip39.c
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/recovery.c
  tiny-firmware/firmware/recovery.h
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/protob/messages.proto
  tiny-firmware/protob/types.proto
Labels: enhancement, stdev, wip

#90 Unable to check signature of message ref #80
  CHANGELOG.md
  skycoin-api/skycoin_crypto.c
  skycoin-api/skycoin_crypto.h
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/gen/bitmaps.h
  tiny-firmware/memory.c
  tiny-firmware/memory.h
  tiny-firmware/protob/messages.options
  tiny-firmware/supervise.h
Labels: Milestone v.1.0.0, bug, critical-security, stdev, wip

#87 Revert removal of recovery seed dry run ref #85
  CHANGELOG.md
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/recovery.c
  tiny-firmware/firmware/recovery.h
  tiny-firmware/protob/messages.proto
Labels: Milestone v.1.0.0, stdev, wip

#92 Remove header metadata from PR template
  .github/pull_request_template.md
  .gitignore
Labels: stdev, wip

#93 [firmware] fixes #78 #91 - Coin fractions in Skywallet display
  Makefile
  skycoin-api/skycoin_crypto.h
  tiny-firmware/Makefile
  tiny-firmware/Makefile.include
  tiny-firmware/firmware/droplet.c
  tiny-firmware/firmware/droplet.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/skyparams.h
  tiny-firmware/firmware/test_droplet.c
  tiny-firmware/firmware/test_droplet.h
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/firmware/test_fsm.h
  tiny-firmware/firmware/test_main.c
  tiny-firmware/protob/types.proto
Labels: stdev, wip

#95 Travis notifications for Telegram bot
  .travis.yml
Labels: stdev, wip

#101 fixes #98 - Remove GetVersion message
  .gitignore
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm.h
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/protob/messages.proto
Labels: firmware, stdev, wip

#97 Create a device label fixes #32
  CHANGELOG.md
  tiny-firmware/bootloader/bootloader.c
  tiny-firmware/emulator/flash.c
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
  tiny-firmware/firmware/fsm_impl.h
  tiny-firmware/firmware/layout2.c
  tiny-firmware/firmware/storage.c
  tiny-firmware/firmware/storage.h
  tiny-firmware/firmware/test_fsm.c
  tiny-firmware/protob/Makefile
  tiny-firmware/serialno.h
Labels: Milestone v.1.0.0, firmware, stdev, wip
