Repository skycoin/hardware-wallet, pull requests merged in 2019-06, with the labels that each got.

#241 [ci] fixes #211 - Do not deploy to Github Releases
  .travis.yml
Labels: ci, stdev, wip

#258 fix fsm_msgSkycoinSignMessage for wiped device ref #257
  FAQ.md
  tiny-firmware/firmware/fsm.c
Labels: Milestone v.1.0.0, bug, enhancement, firmware, good first issue, stdev, wip

#272 Add project banner
  README.md
Labels: Milestone v.1.0.0, doc, stdev, wip

#276 [WIP] deploy on tags ref #269
  .travis.yml
  Makefile
Labels: Milestone v.1.0.0, bug, wip

#279 Remove duplicate instance of fsm_impl.c
  fsm_impl.c
  tiny-firmware/firmware/fsm_impl.c
Labels: Milestone v.1.0.0, firmware, stdev, wip

#277 run pytest from skycoin-api fixes #267
  Makefile
  skycoin-api/Makefile
Labels: Milestone v.1.0.0, bug

#248 secp256k1 ec verify ref #165
  CHANGELOG.md
  skycoin-api/skycoin_crypto.c
  skycoin-api/skycoin_crypto.h
  tiny-firmware/firmware/fsm.c
  tiny-firmware/firmware/fsm_impl.c
Labels: Milestone v.1.0.0, bug, critical-security, enhancement, help wanted, stdev, wip

#275 check bootloader size travis ref #274
  .travis.yml
Labels: Milestone v.1.0.0, bootloader, ci, enhancement
